server:
  port: 9091

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Amol@123
        url: jdbc:mysql://localhost:3306/amol
        username: root
    jpa:
        hibernate:
            ddl-auto: update
      
        show-sql: true
   

    application:
       name: Plan-Api

    boot:
     admin:
      client:
        url: http://localhost:9090/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  
  
    
      
             